#INITIAL SETTINGS
data_directory: ../data/
train_json: train.json
test_json: test.json
size : 2900
source_token_dict : source_token_dict.pickle
source_token_dict_full : source_token_dict_full.pickle
target_token_dict : target_token_dict.pickle
encoder_input : encoder_input.pickle
decoder_input : decoder_input.pickle
output_decoded : output_decoded.pickle
test_processed : test_processed.csv
sample_sub : sample_submission.csv
output_dacon : output_dacon.csv


#Model parameters
model_directory: ../model/
model : model.h5
embed_dim: 64
encoder_num: 3
decoder_num: 3
head_num: 4
hidden_dim: 128
dropout_rate: 0.1
use_same_embed: False
opt : adam
metric : sparse_categorical_crossentropy
epochs : 80
batch_size : 32